name: Docker Branch Image CI

on:
  push:
    branches:
      - '*'
      - '!master'

env:
  CONTAINER_TEST_IMAGE: victoriatreasure-test

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Docker linting
      run: docker run --rm -v "$(pwd)/.hadolint.yaml:/.hadolint.yaml" -i hadolint/hadolint < Dockerfile

    - name: Unit testing
      run: |
        docker build -t $CONTAINER_TEST_IMAGE --target=test .
        docker run --entrypoint="" $CONTAINER_TEST_IMAGE rake test
